# Pipeline to run Bazel tests post-merge onto master
 
# allow CI builds only on master branch by excluding all other branches.
# enforce batch run, which will test all changes at once. This should result in a single run per PR that is merged onto master.
# the single run will include all changes introduced by the PR, instead of testing them sequentially.
trigger: 
  batch: true 
  branches:
    include:
    - master 

pr: none

stages:
- stage: Bazel_Tests
  displayName: Test
  jobs:
  - job: Test
    pool:
      name: 'VMSSPool'
    steps:  
    - script: |
        bazel version
      displayName: 'show bazel version'
    - script: |
        bazel test --test_tag_filters=-benchmark ... 
      displayName: 'run all non-benchmark tests'