# Copyright 2026 The Abseil Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Exposes a CMake source tree as a single Bazel target (open-source only).

rules_foreign_cc's `cmake()` rule needs one label that spans every file CMake
will read. In this repository nearly every directory under `absl/` is a Bazel
package, so no `glob()` can reach across them; the `@googletest` module repo
likewise exposes no target spanning its CMake sources. The repository rule
below mirrors the requested directories and files of a source tree -- this
repository's or a dependency's, selected by `root` -- into an external
repository as per-file symlinks, skipping Bazel package markers, so that a
single root-level `glob(["**"])` covers the whole tree. File contents are
tracked through the symlinks and the mirrored directories are watched, so
changes trigger a re-stage.

MODULE.bazel instantiates it as `@abseil-cpp-cmake-sources` and
`@googletest-cmake-sources`, the `lib_source`s of `//CMake:absl` and
`//CMake:googletest`. Nothing here runs unless one of those repositories is
actually requested.
"""

_BUILD_FILE = """\
# Generated by @abseil-cpp//CMake:cmake_sources.bzl. Do not edit.

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(
        ["**"],
        exclude = ["BUILD.bazel"],
    ),
)
"""

# Files that would turn a mirrored directory into a Bazel package or repository
# boundary, which would stop the root-level glob above.
_SKIPPED_BASENAMES = [
    "BUILD",
    "BUILD.bazel",
    "MODULE.bazel",
    "MODULE.bazel.lock",
    "REPO.bazel",
    "WORKSPACE",
    "WORKSPACE.bazel",
    "WORKSPACE.bzlmod",
]

def _mirror_directory(rctx, src_dir, dst_dir):
    """Symlinks every regular file under src_dir to the same path under dst_dir."""

    # Starlark has no recursion; walk with an explicit stack.
    pending = [(src_dir, dst_dir)]
    for _ in range(1000000):
        if not pending:
            break
        src, dst = pending.pop()
        for child in src.readdir():
            name = child.basename
            if name in _SKIPPED_BASENAMES:
                continue
            if child.is_dir:
                pending.append((child, dst.get_child(name)))
            else:
                rctx.symlink(child, dst.get_child(name))

def _cmake_sources_impl(rctx):
    root = rctx.path(rctx.attr.root).dirname

    for rel_dir in rctx.attr.dirs:
        src_dir = root.get_child(rel_dir)
        if not src_dir.exists:
            fail("cmake_sources: directory does not exist: %s" % rel_dir)
        rctx.watch_tree(src_dir)
        _mirror_directory(rctx, src_dir, rctx.path(rel_dir))

    for rel_file in rctx.attr.files:
        src_file = root.get_child(rel_file)
        if not src_file.exists:
            fail("cmake_sources: file does not exist: %s" % rel_file)
        rctx.watch(src_file)
        rctx.symlink(src_file, rctx.path(rel_file))

    rctx.file("BUILD.bazel", _BUILD_FILE)

cmake_sources = repository_rule(
    implementation = _cmake_sources_impl,
    doc = "Mirrors a CMake source tree into a repository with a single `//:srcs` filegroup.",
    attrs = {
        "root": attr.label(
            doc = "Any file at the root of the tree to mirror; its directory is the root.",
            mandatory = True,
        ),
        "dirs": attr.string_list(
            doc = "Root-relative directories to mirror recursively.",
            mandatory = True,
        ),
        "files": attr.string_list(
            doc = "Root-relative individual files to mirror.",
            default = [],
        ),
    },
)